language: java
jdk:
- oraclejdk8
- openjdk8
env:
  global:
  - secure: DbveaxDMtEP+/Er6ktKCP+P42uDU8xXWRBlVGaqVNU3muaRmmZtj8ngAARxfzY0f9amlJlCavqkEIAumQl9BYKPWIra28ylsLNbzAoCIi8alf9WLgddKwVWsTcZo9+UYocuY6UivJVkofycfFJ1blw/83dWMG0/TiW6s/SrwoDw=
script:
- "./gradle_init.sh"
- gradle assemble
- "./gradle_clean.sh"
- ant
- bin/start.sh
before_script:
- pip install --user codecov
install: true
after_success:
- sh .utility/push-javadoc-to-gh-pages.sh
- bash <(curl -s https://codecov.io/bash)
- mvn clean cobertura:cobertura coveralls:report
- codecov
deploy:
  provider: heroku
  email: robert.mader@posteo.de
  strategy: git
  buildpack: https://github.com/loklak/heroku_buildpack_ant_loklak
  api_key:
    secure: D2o+G28w42F9rDbdeSZQ91TRrm5aLUDyH02Rlh0d+Qov3Qc19WVc5bHuJdc8kYYaeMeG0UcXwpLfvnoAC5Hs03m1sYXMmrq0Z20JUxNx9yRm0p+SD1Y/mAoXkuTX25t9EVxD4YkL03PrSU3K1zIS4xWnzPv7kGl+xQSM68tPL/Q=
  app: loklak-server-dev
  on:
    branch: development
